CREATE USER admin1 WITH PASSWORD 'verysecret1';
CREATE USER admin2 WITH PASSWORD 'verysecret2';
CREATE USER user1  WITH PASSWORD 'secret1';
CREATE USER user2  WITH PASSWORD 'secret2';

CREATE DATABASE dbtest2;
CREATE DATABASE dbtest3;

GRANT ALL PRIVILEGES     ON DATABASE dbtest2 TO admin1;
GRANT CONNECT, TEMPORARY ON DATABASE dbtest2 TO user1;

GRANT ALL PRIVILEGES     ON DATABASE dbtest3 TO admin2;
GRANT CONNECT, TEMPORARY ON DATABASE dbtest3 TO user2;
